# Generated by Django 4.2.15 on 2024-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about_byte2eat', models.TextField()),
                ('about_snackoverflow', models.TextField()),
            ],
        ),
    ]
