# Generated by Django 4.2.15 on 2024-08-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.AddField(
            model_name='review',
            name='food_type',
            field=models.IntegerField(choices=[('Chinese', 'Chinese'), ('Curry', 'Curry'), ('Pizza', 'Pizza'), ('Sushi', 'Sushi'), ('Burgers', 'Burgers'), ('Fish & Chips', 'Fish & Chips'), ('Other', 'Other')], default='Chinese'),
        ),
        migrations.AlterField(
            model_name='review',
            name='takeaway_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Takeaway',
        ),
    ]
